---
# instal docker and docker registry on head node

- name: run setup to gather facts
  hosts: all, localhost
  tasks:
    - name: run setup
      setup:

- name: install docker registry
  hosts: head
  roles:
    - registry

