#!/bin/bash

ID=$1
HOSTNAME=$2
IP=$3
MAC=$4
ROLE=$5

echo "PROVISION $ID $HOSTNAME $IP $MAC $ROLE" >> /etc/maas/ansible/logs/$ID.log

ANSIBLE_ROLES_PATH=/etc/maas/ansible/roles ansible-playbook --private-key=/etc/maas/ansible/id_rsa -i $IP, /etc/maas/ansible/compute-node.yml --skip-tags=interface_config >> /etc/maas/ansible/logs/$ID.out
